### ISSUE TITLE
`sherlock file.md` fails if no error is thrown in script

### ISSUE THREAD

**Issue by bgotink** [arcanis/sherlock#4]
A markdown file that contains a repro that doens't fail leads to a confusing error in sherlock:

```bash
$ yarn sherlock test.md
Type Error [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type undefined
    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    at EntryCommand.execute (/Users/bram/Workspaces/Private/berry/.yarn/cache/@arcanis-sherlock-npm-1.0.25-752547fef2-1.zip/node_modules/@arcanis/sherlock/lib/commands/entry.js:91:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by arcanis** [comment]
Fixed!
